name: macOS CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: brew install polyml qt5 meson ninja capnp mercurial
    - name: repoint
      run: ./repoint install
    - name: configure
      run: PATH=$PATH:/usr/local/opt/qt5/bin meson setup build --buildtype release
    - name: make
      run: ninja -C build
    - name: test
      run: meson test -C build
    - name: deploy-app
      run: QTDIR=/usr/local/opt/qt5 ./deploy/macos/deploy.sh build
    - name: check
      run: |
        otool -L ./"Piano Precision.app/Contents/MacOS/Piano Precision"
        ./"Piano Precision.app/Contents/MacOS/Piano Precision" --version
